package sealab.burt.server;

public enum StateVariable {
    //general ones
    NEXT_INTENTS, CURRENT_MESSAGE, SESSION_ID, PARTICIPANT_ID, PARTICIPANT_VALIDATED,

    //app variables
    APP, APP_VERSION, APP_ASKED, APP_CONFIRMATION,

    //ob variables
    COLLECTING_OB, OB_SCREEN_SELECTED,

    //eb variables
    COLLECTING_EB,

    //s2r variables
    COLLECTING_S2R, CONFIRM_LAST_STEP, DISAMBIGUATE_S2R,

    //quality checkers/results
    EB_CHECKER, S2R_CHECKER, OB_CHECKER, EB_QUALITY_RESULT, OB_QUALITY_RESULT, S2R_QUALITY_RESULT,

    //report summary
    REPORT_OB, REPORT_EB, REPORT_S2R, EB_SCREEN, EB_DESCRIPTION, OB_SCREEN, OB_DESCRIPTION, OB_QUALITY_FEEDBACK,
    S2R_DESCRIPTION, S2R_SCREEN, REPORT_GENERATED
}
