package sealab.burt.server;

public enum StateVariable {

    //general ones
    NEXT_INTENTS, CURRENT_MESSAGE, SESSION_ID, PARTICIPANT_ID, PARTICIPANT_VALIDATED, PARTICIPANT_ASKED,
    CONFIRM_END_CONVERSATION, LAST_ACTION, ACTION_NEGATIVE_END_CONVERSATION, LAST_MESSAGE,
    MSG_NEGATIVE_END_CONVERSATION, CONFIRM_END_CONVERSATION_NEGATIVE,

    //app variables
    APP_NAME, APP_VERSION, APP_PACKAGE, APP_ASKED,

    //ob variables
    OB_SCREEN_SELECTED, OB_STATE, OB_DESCRIPTION, OB_MATCHED_CONFIRMATION,
    CURRENT_OB_SCREEN_POSITION,

    //eb variables
    EB_SCREEN_CONFIRMATION, EB_DESCRIPTION, EB_STATE,

    //s2r general variables:
    COLLECTING_S2R, CONFIRM_LAST_STEP, S2R_MATCHED_CONFIRMATION, S2R_MATCHED_MSG, COLLECTING_FIRST_S2R,
    ASKED_TO_WRITE_S2R,

    //s2r missing
    S2R_ALL_MISSING,

    //s2r prediction
    PREDICTING_S2R, PREDICTED_S2R_NUMBER_OF_PATHS, PREDICTED_S2R_PATHS_WITH_LOOPS, PREDICTED_S2R_CURRENT_PATH,
    NON_SELECTED_PREDICTED_S2R,

    //delete step
    DELETE_STEP_MSG,

    //quality checkers/results
    EB_CHECKER, S2R_CHECKER, OB_CHECKER, EB_QUALITY_RESULT, OB_QUALITY_RESULT, S2R_QUALITY_RESULT,

    //report summary
    REPORT_OB, REPORT_EB, REPORT_S2R, REPORT_GENERATED,

    //reporting time
    REPORTING_START_TIME, REPORTING_END_TIME,

    NEW_PREDICTION_CONFIRMATION, TIPS

}
